# Basic
title: 青皮
subtitle: 工作难
welcome_message: 欢迎光临,来的点个赞
description: 行不行
creator: <a href="http://yinqp.cc/">@netabc</a>

url: "http://yinqp.cc/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/netabc'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: netabc
    github: netabc
    twitter: netabc
    gplus: 107108267983477358170
    mail: imgpng@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
